all:
  hosts:
    openvpn_proxy:
      ansible_host: 15.236.39.42
      ansible_user: admin
    openvpn1:
      ansible_host: 15.237.214.51
      ansible_user: admin
    openvpn2:
      ansible_host: 15.237.185.130
      ansible_user: admin
