all:
  hosts:
    openvpn_proxy:
      ansible_host: 13.38.69.223
      ansible_user: admin
    openvpn1:
      ansible_host: 15.188.77.53
      ansible_user: admin
    openvpn2:
      ansible_host: 13.39.233.19
      ansible_user: admin    
