redteam:
  vars:
    vpn_port: 1194
  children:
    roundrobin:
      children:
        roundrobin_out:
          children:
            master:
              hosts:
                openvpn1:
            slave:
              hosts:
                openvpn2:
        roundrobin_in:
          hosts:
            openvpn_proxy:
              vpn_clients: ['client1_roundrobin', 'client2_roundrobin'] # Add more clients if needed
              